### ISSUE TITLE
`400 Bad Request` response: Invalid Time Specification

### ISSUE THREAD

**Issue by fishnyc22** [MatthewHallCom/pirate-weather-php#1]
Found this repo when trying to port darksky over to pirateweather. Thanks for working on this. I am just trying it out and am getting an error: I get this with teh code below and with your demo code with static times set. 
```
Got error 'PHP message: PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `GET https://api.pirateweather.net/forecast/MYAPIKEY/37.936,-107.803,2023-05-04T00:00:00?exclude=currently,minutely,hourly,alerts,flags` resulted in a `400 Bad Request` response:\n"Invalid Time Specification"\n in 
```
Any idea why? here's my code: 

```
$timeMachine = (new PirateWeather('MYAPIKEY'))
->location(get_field("latitude", $project_id), get_field("longitude", $project_id))
->timeMachine(date("Y-m-d", strtotime(get_field("log_date"))), 'daily');

echo $timeMachine->daily()->summary();
```

I'm trying to port over this code: 
```
$args = array(
'api_key' 	=> 'MYAPIKEY', // Enter your API key
'latitude'	=> get_field("latitude", $project_id), // enter the longitude
'longitude'	=> get_field("longitude", $project_id), // enter the latitude
'query'		=> array( 'units' => 'us', 'exclude' => 'flags,hourly' ),
'cache_time' => 6 * MONTH_IN_SECONDS,
'time'		=> strtotime(date("Y-m-d", strtotime(get_field("log_date"))) . ' 12:00:00' )
);
									
$forecast = new DarkSky\Forecast( $args );
```

Thanks!

**Comment by MatthewHallCom** [comment]
I will take a look! I haven't used the Time Machine endpoints with Pirate Weather yet

**Comment by MatthewHallCom** [comment]
Looks like Pirate Weather uses a different API endpoint for Time Machine queries. I've released a new version of the package that makes it use that API endpoint!

It does look like the Pirate Weather Time Machine doesn't yet have historical data for `2023-05-04` in your test query. They only update it monthly and don't have May data in there yet. You'll have to raise an issue with them if you want them to expand the Time Machine date range.

Please let me know if there is any other issues you find!
